### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by TalAmuyal** [eddieantonio/sentinel#7]
Hi,

Looks like a neat package, any reason not to release a 1.0.0 version?

**Comment by eddieantonio** [comment]
Everybody knows that blazing-fast 🚀 libraries must use [ZeroVer](https://0ver.org/) versioning 😂 😂 😂 

You're right — I'll release 1.0.0, since there's not much to this package. It might as well have a stable version!  Maybe at some point a similar facility will make it into the standard library, making this package obsolete (see [PEP 661](https://peps.python.org/pep-0661/)).

**Comment by TalAmuyal** [comment]
Great!
I believe it should indeed be part of the standard library.
Thanks! :D
